name: Run Python Script

on:
  schedule:
    - cron: '0 */8 * * *'  # Ejecutar cada 8 horas

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download previous data (if any)
        uses: actions/download-artifact@v4
        with:
          name: crypto-data
        continue-on-error: true  # Continúa incluso si no encuentra un artifact

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run script
        run: |
          python main.py

      - name: Upload Update crypto data
        uses: actions/upload-artifact@v4
        with:
          name: crypto-data
          path: crypto_data.csv
