name: Run Python Script

on:
  schedule:
    - cron: '0 */8 * * *'  # Ejecutar cada 8 horas

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache crypto data
        id: cache-crypto-data
        uses: actions/cache@v3
        with:
          path: crypto_data.csv
          key: ${{ runner.os }}-crypto-data

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run script
        run: |
          python main.py

      - name: Upload Update crypto data
        uses: actions/upload-artifact@v4
        with:
          name: crypto-data
          path: crypto_data.csv
